### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by schildbach** [JereKuusela/valheim-upgrade_world#1]
While reading your docs at https://valheim.thunderstore.io/package/JereKuusela/Upgrade_World/, I (someone without modding experience) came upon a couple of questions. I'd like to write them down here so that perhaps the docs can be improved.

1. What exactly is a zone? I thought it might be an (irregular) instance of a biome, so e.g. one "Mountains". Someone in the chat said it might be a rectangular tile, like the tiles in Google Maps. What's correct?
2. What exactly is a location?
3. What's the "center of the world"? Is that the same as the "spawn"?
3. What exactly is the difference between the `upgrade` and the `nuke` commands? Someone in chat said they do basically the same, only nuke ignores your inclusion and exclusion config.
4. What does "explored area" mean in the context of multiple players, which all have their own explored area?
5. Do all currently logged-in players cause a "currently loaded area" which is consequently excluded from nuking, or does only one player have that?
6. Does the plugin need to be applied to a client or to the server?
7. How to measure distances in-game in order to get coordinates and radii right?

No need to answer here. Ideally just put it into the documentation so that everyone profits.

Thanks for your work on the upgrader!

**Comment by JereKuusela** [comment]
Hey, thanks for the questions.

I will give quick answers here and try to improve docs later.

1. Each zone is a 64 m x 64 m tile, see https://valheim.fandom.com/wiki/Zones for more info.
2. Locations are special places like rune stones, dungeon entrances or abandoned houses that are placed on the world.
3. Center of the world is the middle of map. Spawn location is usually close it to it but not necessarily at it.
4. Upgrade command is intended to gracefully add new content to the world. In this case it only places tar pits and only destroys things that existed on their place. Nuke command will destroy and restore everything back to how it was generated.
5. Explored areas in this case means areas that have been generated (up to 500 meters from where players have been).
6. The mod is intended to be single player only. I think "currently loaded area" will include all players but haven't tested.
7. Client only (single player only).
8. Devcommand pos gives current coordinates but this is not very easy. I have been thinking about adding coordinates to the minimap view.

By the way, which chat are you talking about?

**Comment by schildbach** [comment]
Thanks!

ad 4. I take it if nuked terrain gets generated it will take the new rules (expansions) into account, so you'd get new stuff?

Multi-player vs. Single player: That's bad news for our group. So I guess we need to look for a tool that can upgrade multiplayer worlds.

**Comment by JereKuusela** [comment]
Nuked terrain will generate with new rules (if you call genloc command after, the nuke command informs about this after the operation).

The intended way to use this is to load the world in single player, upgrade/nuke wanted areas and then remove the mod.

**Comment by JereKuusela** [comment]
Uploaded a new version with a hopefully improved documentation. But please let me know if anything still needs tweaking.
