### ISSUE TITLE
[Question] Possible to mistlands_worldgen only in a specific area?

### ISSUE THREAD

**Issue by himpich** [JereKuusela/valheim-upgrade_world#16]
I know I can reset zones (make them unrendered) (zone_reset / world_reset).

All worldgen commands (which should make mistlands more availble) don't accept distance limitations, is that correct?

to be more precise:
![image](https://user-images.githubusercontent.com/6817957/207642665-ee02f141-f6ff-4764-8cc2-44fc093291fc.png)
I would like to have this AREA regenerated with the current algorhythm (mistlands) and I guess there will be much more mistlands than there are now. Is that possible?

**Comment by JereKuusela** [comment]
World generator is a world side setting, it will affect the entire world.

**Comment by himpich** [comment]
in other words: no chance for my goal?
