### ISSUE TITLE
Mesh can not have more than 65000 vertices

### ISSUE THREAD

**Issue by z00z9** [JereKuusela/valheim-upgrade_world#2]
Using [JTV](https://valheim.thunderstore.io/package/thedefside/Journey_To_Valhalla/) and [EpicValheimAdditions](https://valheim.thunderstore.io/package/Huntardys/EpicValheimsAdditions/), I get the following error when inputting

`place_locations clear Vegvisir_BlazingDamnedOne`

[Error: Unity Log] ArgumentException: Mesh can not have more than 65000 vertices
UnityEngine.UI.VertexHelper.FillMesh (UnityEngine.Mesh mesh) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Graphic.DoMeshGeneration () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Graphic.UpdateGeometry () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Text.UpdateGeometry () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.Graphic.Rebuild (UnityEngine.UI.CanvasUpdate update) (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.UI.CanvasUpdateRegistry.PerformUpdate () (at <5abdc278a459476dabe36f8ad65ea091>:0)
UnityEngine.Canvas.SendWillRenderCanvases()

**Comment by JereKuusela** [comment]
Do you have more details? Inputting the command shouldn't do anything before you do `start` command.

**Comment by z00z9** [comment]
I forgot to write that yes that was after inputting start after the place_locations.

When running JTV, if you install it after a world has been created you're supposed to run the following commands:

place_locations clear SvartalfrQueenAltar_New
start
place_locations clear JotunnAltar
start
place_locations clear BlazingDamnedOneAltar
start
place_locations clear Vegvisir_SvartalfrQueen
start
place_locations clear Vegvisir_Jotunn
start
place_locations clear Vegvisir_BlazingDamnedOne
start

All of the above executed without problems, except for `place_locations clear Vegvisir_BlazingDamnedOne
start`

Also, I have been running these commands directly on the dedicated server via your server devcommands [plugin](https://valheim.thunderstore.io/package/JereKuusela/Server_devcommands/) - I know that's not what it says in the instructions (says to run local and transfer it over), but the rest of the commands worked so I figured it would be ok.

**Comment by JereKuusela** [comment]
One big problem would be that the locations are registered on the server. Your client won't know which positions are unused and might try to overlap them.

**Comment by z00z9** [comment]
Ok, thank you
