### ISSUE TITLE
[Question] why upgrade EVA causes performance issue on mistlands update (0.212.9)

### ISSUE THREAD

**Issue by sELVEE** [JereKuusela/valheim-upgrade_world#24]
Running upgrade EVA causes performance issue in my case (I found on one of the discords also few more ppl having same issue). Process lasts for long time - it ends up successfuly but somehow it generates a lot of instances (F2) that causes fps drops and perf issues. Don't know if it's due to my PC, world or anything on my site but after upgrading map is unplayable. In attachments photo with 2nd step of upgrade (it places missing locations after adding vegetation). In top left corner you can see fps count :/
![image](https://user-images.githubusercontent.com/18482105/208641326-f8ad72f9-9b8c-4bcb-a4e2-4f4eb9607036.png)

I see I'm not the only one having same issue, maybe it's due to mistlands update - looks like, EVA creators said that could be the reason

**Comment by JereKuusela** [comment]
Thanks for the report. This should now work with the version 1.25. Can you try?

**Comment by sELVEE** [comment]
On it, I'll let you know after upgrading :)

Hard to tell, lags are not appearing anymore so looks like it worked :) But I have to verify also altairs and everything else

**Comment by sELVEE** [comment]
Verified on JTV 1.1.5, Valheim 0.212.9. Works fine, missing altairs and structures appeared correctly, base untouched, no known issues atm
