### ISSUE TITLE
locations_reset does not remove the old spawners?

### ISSUE THREAD

**Issue by himpich** [JereKuusela/valheim-upgrade_world#25]
Graves in the woods and mines in the mistlands have guards (skeletons + seekers) which belong to the location.

If I use locations_reset via your cronjob mod, the guards stay and it looks like the new guard spawns are added (if they are in another place as the old one, e.g. due to random rotation of the location).
Lots of seeker (red) spawners:
![image](https://user-images.githubusercontent.com/6817957/211192207-70a1dcf2-b838-44f3-90cd-d4fe09b43f3a.png)

Lots of skeleton spawners (yellow) (not all shown) (and skeletons):
![image](https://user-images.githubusercontent.com/6817957/211192230-c5961e8e-e37b-4813-a242-9c237a8d62a1.png)

A "normal" burrial site:
![image](https://user-images.githubusercontent.com/6817957/211192280-c6ae7d88-7d5c-49e7-af6d-e7bdeabe577b.png)

I guess, that new guards wouldn't spawn on the reset, if the guard-spawners would be in the same place, but due to new spawner-locations (e.g. location rotation changed), the new spawners are at different places and spawn new guards?

**Comment by JereKuusela** [comment]
It only removes what is around the location. So if the enemies have wandered then they would be duplicated. I can try fixing this at some point but won't fix already duplicated enemies.
