### ISSUE TITLE
v 1.28.0 reset_zones deletes player structures

### ISSUE THREAD

**Issue by awdwyn** [JereKuusela/valheim-upgrade_world#26]
Using the newly updated 1.28 version to reset_zones (to add new spawners from ValHarvest) and standing in front of my house I watched the world disappear and be rebuilt, however my house was gone when it finished. I tried both with default settings and safeZones=10 set with the same results. No errors or comments in the log. Downgrading to 1.27 caused the process to work as expected (again with default settings).

Thank you for the recommendation to backup my world 😄

**Comment by JereKuusela** [comment]
Thanks for the report, should be fixed now.
