### ISSUE TITLE
Does re-running mountain_caves re-generate existing explored caves?

### ISSUE THREAD

**Issue by trak3r** [JereKuusela/valheim-upgrade_world#27]
From their recent patch notes:

> "Fish in mountain caves will respawn correctly, and small additional lake added"

From your documentation:

> "mountain_caves: Spawns mountain caves to already explored areas."

It looks like they are changing the way frost caves are generated, so my question is will re-running your `mountain_caves` command re-generate existing explored caves with the new "lakes"?

Thank you.

**Comment by JereKuusela** [comment]
You would need to use locations_reset command to reset already spawned locations.

**Comment by trak3r** [comment]
got it. thanks @JereKuusela
