### ISSUE TITLE
Many Frosted Caves vanished from my world :-( [Bug? not sure.]

### ISSUE THREAD

**Issue by l1m3r** [JereKuusela/valheim-upgrade_world#28]
@JereKuusela - Thank you for this awesome mod! :-) Should be integrated in VH. :+1: 

![20230213011957_1](https://user-images.githubusercontent.com/18506112/218604907-98f90a33-4b2b-4aec-9016-db1298ef5513.jpg)
This ^^ is just one example where an entrance to a FC was and all that's remaining now is the skeleton remains.

I don't know exactly when it happened but this is a rough timeline:
1. 220301 - **VH update (0.207.2)**: FCs added.
2. 220601 - Made backup: **it already contained some FCs**. (or do the get added automatically by VH even without UW?!)
3. 221206 - **VH update (0.212.7)**: Mistlands release.
4. 221216 ~ Made Backup. -> Used UW. Side effect was all my **Surtlings spawners went "dry"** again (were dug down to be slightly below the water line previously).
5. 230207 - **VH update (0.213.4)**: RJ respawns in IMs.
6. 230207 - new backup. -> trying to get already explored IMs to respawn RJ. -> `locations_reset Mistlands_DvergrTownEntrance1,Mistlands_DvergrTownEntrance2 pos=x,y max=30` with x,y being coordinates near a single IM. It works in SP (not sure about MP) - flipped the entrance of the one test IM around. Dismantled shed & rebuild. Funny effect when standing on top of a shed that vanishes below your eyes ;-).
7. Tried ploppy's Mistland update to T3kla's ["Dungeon Reset"-mod](https://www.nexusmods.com/valheim/mods/2069?tab=description) on another test IM and it seems to work in only resetting the IMs internals without effecting the outside. And jelly++ respawning on its own afterwards.
8. 230212 ~ noticed a lot of FCs vanished from my mountains.

Between 4. and 5. I explored plenty of new Mistland area and more. Including a **small mountain biome with six FCs** where now only two remain. :-(
I've checked another mountain I had previously explored at 2. - It had only two FCs then (checked from backup) but during those recent explorations I found >=7 FCs! Now it's back to only two FCs :-(

Don't have a backup from anywhen in between 4. and 6. unfortunately.

Is this maybe related to [the Upgrade World version that didn't check for "enabled" flag](https://forums.nexusmods.com/index.php?/topic/10508893-upgrade-world/page-28#entry121370505)? As in when I upgraded the Mistlands (at 4.) many _not enabled_ FCs got added too? I don't remember the exact UpgradeWorld command I used but I do remember being surprised that it obviously disabled my coal farms by raising ground below the spawners above the water level again (see 4.)
But I don't get any [related errors (or FPS  drops)](https://forums.nexusmods.com/index.php?/topic/10508893-upgrade-world/page-26#entry120928971) in any logs.

Or some wired interaction between UW and DungeonReset (which was limited to interacting with IMs only I'm sure)?

I tried re-adding one vanished FC manually but the commands didn't work.
```
locations_list pos=2711,5045 max=30
-> ... (found one MountainCave01 location)
locations_reset MountainCave01 pos=2711,5045 max=30
locations_reset MountainCave01 pos=2711,5045 max=30 force
-> ..., 1 skipped by not having the location.

locations_add MountainCave01 pos=2711,5045 max=30 force
start
-> 
   Redistribute .... may take a while...
   [Info   : Unity Log] 02/13/2023 06:53:15: Old location found MountainCave01 x 76
   0 locations M... added ... (total ...: 500).
   Spawn missing locations: 1/1
   Spawn missing locations completed. 0 locations spawned to the world.
```
The vanished location was found but refused to reset because of nearby building.
`force` lead to `... not having the location`(?) and I don't understand the feedback from `locations_add`...

Is there any (safe) way to recreate them? (set enabled to true?)

UW = UpgradeWorld
FC = Frost Cave
IM = Infested Mine
RJ = Royal Jelly
SP = SinglePlayer
MP = MultiP.

**Comment by JereKuusela** [comment]
MountainCave01 is not the correct cave but the unused version of it. So the last patch should have removed the entrances as the objects no longer exist in the game.

I could add location swap functionality so that you could replace the entrances.

**Comment by l1m3r** [comment]
I remember wondering about the skeletons there at the entrances - which looked kinda different too (more like the Troll cave entrances)...

> the last patch should have removed the entrances

The last VH patch (automatically) or UpgradeWorld?

I'd like to see that functionality to restore ~5 of the ~9 _missing_ FCs in my world but don't make it a high priority if/when you add it.
Reasons is by now I've come to terms with the _loss_ :-). I had already raided ~4-5 of those mines so I wouldn't restore them now and I already got my Fenris armor (if and when my friends rejoin it will just take longer...).

What I'm more interested in right now is satisfying my curiosity on how this happened (and making sure it doesn't happen again (with other crypts/mines)).

And why the ground below my Surtling spawners got raised above water level (Mistland UW at 4., noticed at 221220):
![20221220190120_1](https://user-images.githubusercontent.com/18506112/218766246-722eb15a-d328-4ffd-93e3-0cee7e6d409a.jpg)

**Comment by JereKuusela** [comment]
The latest Valheim patch removed some unused locations. Unfortunately not unused for some. 😁

Most likely your world had more Frost Caves than intended.

If you used the world gen upgrade command, that would reset areas past 5000 meters because biomes would have potentially changed. The standard upgrade command shouldn't affect Swamps.

**Comment by JereKuusela** [comment]
New version has locations_swap. You can try `locations_swap MountainCave02,MountainCave01` to swap 1 to 2.

**Comment by l1m3r** [comment]
This is getting more wired by the minute...
Tried this:

1. `locations_list pos=2562,4984 max=30` -> got one `MountainCave01`.
2. `locations_swap MountainCave02,MountainCave01 pos=2562,4984 max=30` -> An entrance to a FC was created and I was trapped in the empty space inside. :-) (happened immediately - would have expected this command to require a `start`.)
3. entering the FC doesn't work. The "entering FC" _animation_ starts but I get **BLOCKED** in the middle of the screen and return to outside the cave directly in front of the entrance (as if I had left it normally).
4. `locations_list pos=2562,4984 max=30` -> still returns `MountainCave01` ?!
5. `locations_reset MountainCave02,MountainCave01 pos=2562,4984 max=30` -> doesn't work "location doesn't exist".
6. `locations_reset pos=2562,4984 max=30` finds a location to reset but _start_ results in:
```
NullReferenceException: Object reference not set to an instance of an object
  at UpgradeWorld.Helper.ClearAreaForLocation (Vector2i zone, ZoneSystem+LocationInstance location, System.Boolean force) [0x00000] in <0888e82227124290848d59ad68f6bd26>:0 
  at UpgradeWorld.LocationOperation.SpawnLocation (Vector2i zone, ZoneSystem+LocationInstance location, System.Boolean clear, System.Boolean forceClear) [0x00029] in <0888e82227124290848d59ad68f6bd26>:0 
  at UpgradeWorld.RegenerateLocations.ExecuteLocation (Vector2i zone, ZoneSystem+LocationInstance location) [0x00023] in <0888e82227124290848d59ad68f6bd26>:0 
  at UpgradeWorld.LocationOperation.ExecuteZone (Vector2i zone) [0x00038] in <0888e82227124290848d59ad68f6bd26>:0 
  at UpgradeWorld.ZoneOperation.OnExecute () [0x00029] in <0888e82227124290848d59ad68f6bd26>:0 
  at UpgradeWorld.ExecutedOperation.Execute () [0x00015] in <0888e82227124290848d59ad68f6bd26>:0 
  at UpgradeWorld.Executor.Execute () [0x0008f] in <0888e82227124290848d59ad68f6bd26>:0 
  at UpgradeWorld.UpgradeWorld.Execute () [0x00000] in <0888e82227124290848d59ad68f6bd26>:0
``` 

Do I need to `location_register` and/or `locations_add` too?

And I think the combination of UW and [DungeonReset](https://www.nexusmods.com/valheim/mods/2069?tab=description) may have borked something in my map.
I don't get any (previously unknown) fatal/relevant errors but when I teleport to the either mountain biome with the missing FCs i get some (>1) errors exactly like `[Warning: Unity Log] 02/17/2023 23:37:02: Missing location:-1218789637` (only the date/time changes) - right before several:
```
Loading dungeon
Dungeon loaded <different ints here>
Dungeon load time xx,y... ms
```

And I'm 100% sure I reset at least one IM with the DungeonReset mod but now when I try that on another IM it can't find it anymore.

**Comment by JereKuusela** [comment]
Whether the command requires "start" depends on the command base type. It would make sense if all required start but I haven't got time to do that yet.

I guess trying the swap was worth a shot. Probably the dungeon entrances don't exactly match so you can't get into the old dungeon.

If locations list still returns MountainCave01 then it wasn't changed in the location database. I can upload a new version later that might work better.

You can't reset non-existing locations so locations_reset MountainCave01 won't work. There is no way for the game to know what to spawn in place of a non-existing location.

Missing location:-1218789637 means that there is a non-existing location. Probably MountainCave01.

And yes, world_clean removes missing things. 😁

**Comment by l1m3r** [comment]
> I can upload a new version later that might work better.

I'm currently not playing Valheim anymore (for some time, maybe until the next update) but I'll gladly test another UW version to *fix* those dungeons. :-)

<br />

> Probably the dungeon entrances don't exactly match so you can't get into the old dungeon.

Do you mean graphically/geometrically? It was my understanding that the dungeons aren't inside or connected to the *overworld* except through those entrances which are basically portals (I assume the last part). Thus no "*exact match*" at any dungeon by definition (just some id-connection in the data).
Usually the players position on the map is basically the same before and after *using* a dungeon entrance but I have noticed some dungeons were the positions were noticeably off (marked the dungeon after entering it and after exiting noticed a too big difference between marked and actual position).
Maybe I noticed that exactly on those missing FCs. So I'm nor sure about my assumptions...

How exactly do they need to match? AFAICT the new entrance was pretty much exactly where the original one was (maybe ~2m lower because the skeleton remains were kinda floating in the air I think).

And why "*into the **old** dungeon*"? I've never been in half of those FCs, just marked the entrances for later exploration. So I don't mind if they are newly generated. (I assume when the entrances were removed the same happened to the innards.)

<br />

> You can't reset non-existing locations so locations_reset MountainCave01 won't work.

I know that. But before trying the *swap* command `locations_reset` returned a normal error (sth. like: "_0 zones: XYZ skipped by the command, **1 skipped by not having the location**_"). After the *swap* the same `locations_reset` resulted in that ^^ `NullReferenceException` instead.
So the locations were partially swapped (as in UW *thought* the location did exist after the swap and tried to `locations_reset` it but it actually didn't exist)?

Would like to get a copy of my world to investigate directly? Plus the commands I used and location coordinates and so on.
Btw. do you know of a way to get all the console **input** and output into a/the log file? right now all I have are screenshots of some of those console interactions.

<br />

> And yes, world_clean removes missing things.

Nothing can remove something that's already missing... ;-)
I know this from my own explanations of what some code I wrote does: They aren't nearly as clearly understandable and unambiguous from the outside (how can `world_clean` remove stuff that's already missing? I guess it's gone from some db but not the other but still...).
I think this might apply to (parts of) your `README.md` too (I've been thinking about forking it and making a pull request with some changes for some time now but so far I haven't found the required internal motivation :-/ ).
