### ISSUE TITLE
[help] Reset single infested mine

### ISSUE THREAD

**Issue by Quentin-ctrL** [JereKuusela/valheim-upgrade_world#30]
Hi,

I'm trying to reset a single infested mine (no respawn bug).
To target the dungeon and reset the dungeon : 
```
# get current position
pos  
Player position (X,Y,Z):(5450,47,2890)  

# list nearby infested mine
locations_list pos=5450,2890 distance=0-50  
Misltands_DvergrTownEntrance1: (5440,49,2880) Mistlands

# reset nearby infested mine
locations_reset Misltands_DvergrTownEntrance1 pos=5440,2880 distance=0-1
```  
I'm right to reset this single dungeon ? 
Or there is no easier way to target nearby dungeon ?

I had to use 'force' argument, couldn't find remaining 'player based items'. It worked that way.

Thanks for your work.

**Comment by JereKuusela** [comment]
You can do

`locations_reset zone`

to reset the location in your current zone.
