### ISSUE TITLE
[BUG?] execute "objects_list SpearCarapace" -> server logs false & changing coordinates.

### ISSUE THREAD

**Issue by l1m3r** [JereKuusela/valheim-upgrade_world#32]
I used `objects_list SpearCarapace` to locate a single missing spear and found it at the location printed in the local F5 game console. *thumbsup*

The server logged this:
```
[Info   : Unity Log] <NonsenseEndianDATE> <TIME>: <SteamID>/<MyNickName> (2374, 4880, 65): objects_list SpearCarapace
[Info   : Unity Log] <NonsenseEndianDATE> <TIME>: <SteamID>/<MyNickName> (2383, 4905, 75): objects_list SpearCarapace
[Info   : Unity Log] <NonsenseEndianDATE> <TIME>: <SteamID>/<MyNickName> (2383, 4905, 75): objects_list SpearCarapace
[Info   : Unity Log] <NonsenseEndianDATE> <TIME>: <SteamID>/<MyNickName> (2449, 5001, 173): objects_list SpearCarapace
```
Note the changing coordinates and none of those were the right ones. The last line was closest I think but I only remember Y="4999,?"
I executed the command four times because I used the server log's information and didn't find anything there...

**Comment by JereKuusela** [comment]
That is your position when executing the command.

**Comment by l1m3r** [comment]
lol, thx.
Guess I thought myself in a corner there.
seems so obvious now (doh). ;-)
