### ISSUE TITLE
Ashland update

### ISSUE THREAD

**Issue by Twerkey86** [JereKuusela/valheim-upgrade_world#38]
Since the update my base up in the Deep North is flying, i tried this mod but it didnt fix it, seems like the north also got effected by the map changes.

**Comment by JereKuusela** [comment]
Yes, this is correct. The gap was added to both Ashlands and Deep North.

**Comment by Twerkey86** [comment]
Oh it would be so good if you could =) i was heartbroken when i heard the base breaking apart when i spawned in without knowing this thing 😄

**Comment by JereKuusela** [comment]
So you rather want your base entirely gone?

**Comment by Twerkey86** [comment]
Oh, so this mod dosent make the map be as it was before the Ashland update?

**Comment by JereKuusela** [comment]
Nope. If you want to stay in the old game version, then you must not update the game itself.
