### ISSUE TITLE
Config File missing?

### ISSUE THREAD

**Issue by johanBostrom92** [JereKuusela/valheim-upgrade_world#39]
Hey, 

I've been trying to access the config file to make changes to my settings (and be a little more aggressive in safe zones) but I'm unable to locate the file, following the instruction I tried locating the config file in: D:\Steam\steamapps\common\Valheim\BepInEx\config, but in config I only find BepInEx.cfg and displayinfo.cfg, help appreciated.

**Comment by JereKuusela** [comment]
You are probably using a mod manager which saves them somewhere else.
