### ISSUE TITLE
So only upgrading some things is supported now?

### ISSUE THREAD

**Issue by Sketaful** [JereKuusela/valheim-upgrade_world#42]
Needed to do a full upgrade of my server since I've changed so much in configs of different mods adding clutter and stuff but...

Seem like this mod only support upgrading of Ashlands, Deepnorth, Mistlands, and Mountain caves? 

Is this all it supports now or do I just have a problem with my  install?

**Comment by JereKuusela** [comment]
Check the documentation. For example zones_reset
