### ISSUE TITLE
bug: `chance` parameter is ignored in case of multi-zone `locations_reset`

### ISSUE THREAD

**Issue by nbusseneau** [JereKuusela/valheim-upgrade_world#44]
Hey, thanks for all your mods 😄 

(Posted this earlier on the Discord but there was so much volume, reposting here instead.)

There's a bug with `locations_reset` + the `chance` parameter: when running on multiple zones, the `chance` parameter is ignored for all locations in non-local zones, i.e. all locations outside of the local zone get reset no matter the value of the `chance` parameter. The local zone still respects the chance parameter (just like when running on a single zone).

I'm thinking maybe the issue is that the chance parameter is not passed down to other zones when running a multi-zone `locations_reset` command?

## Reproduction steps

- Go somewhere with locations.
- Run `locations_reset zone chance=50 start` a couple times => the location in the zone has a 50% chance to be reset, as expected.
- Run `locations_reset zone chance=50 maxDistance=2 start` a couple times => all of the locations in the non-local zone get reset every time, where I expected only about half of them to get reset (similar to how `vegetation_reset` works).

### Single zone, `chance=50` is respected 

https://github.com/user-attachments/assets/cb808585-5433-48df-951f-633ec4920f9a

### Multiple zones, `chance=50` is not respected, all locations in non-local zones are reset at all times (but local zone does respect the chance still)

https://github.com/user-attachments/assets/fb7b5311-f219-4405-9295-972e9ca2afb0

**Comment by JereKuusela** [comment]
This should be fixed in the latest update.

**Comment by nbusseneau** [comment]
Cheers, will try it out.
